# Default values for Acceptance stage of sample-k8s-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  hosts:
    - host: gha-demo-k8s-node.ingress.piper-k8s.piper-cd.shoot.canary.k8s-hana.ondemand.com
      paths: 
        - /
