name: Mirror to Internal GH

# yamllint disable-line rule:truthy
on:
  delete:
  push:
    branches-ignore:
      - 'renovate/**'
    tags:
      - 'v*'
      - 'v*.*'
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to mirror'
        required: true

# For dynamic naming of the workflow runs
run-name: >-
  Trigger ${{ github.event_name }}:
  ${{
    github.event_name == 'push' && github.ref ||
    github.event_name == 'delete' && github.event.ref ||
    ''
  }}

# This will ensure that only one workflow is active for each event (and it's ref) by canceling previously triggered active workflow runs.
# For example, if there are multiple pushes to a branch in a short time frame, only the last one will be processed, the rest will be canceled.\
# See docs: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event_name }}-${{
      github.event_name == 'push' && github.ref ||
      github.event_name == 'delete' && github.event.ref ||
      ''
    }}
  cancel-in-progress: true

jobs:
  mirror:
    uses: project-piper/.github/.github/workflows/reusable-mirror.yml@main
    with:
      source_github_host: 'github.tools.sap'
      source_repo: ${{ github.repository }}
      target_github_host: 'github.wdf.sap.corp'
      target_repo: ${{ github.repository }}
      source_branch: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads') && github.ref_name || inputs.branch || '' }}
      tag_name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.ref_name || inputs.branch || '' }}
      delete_ref: ${{ github.event_name == 'delete' && github.event.ref || '' }}
    secrets:
      TARGET_GITHUB_TOKEN: ${{ secrets.GH_WDF_TOKEN }}
      UPTIME_PUSH_TOKEN: ${{ secrets.UPTIME_PUSH_TOKEN_MIRROR }}
