# If you rename this workflow, consider renaming it in publishing workflow publish_task.yml
# in order event trigger to work properly
name: Pull Request Package (dev)

on:
  workflow_dispatch:
    inputs:
      skip_unit_tests:
        type: boolean
        default: false
        description: Skip unit tests

  pull_request:
    branches:
      - main

jobs:
  versioning:  # Determines next development version
    if: ${{ github.actor != 'ospo-renovate[bot]' }}
    uses: ./.github/workflows/versioning.yml
    with:
      release: false

  unit-tests:
    if: ${{ !inputs.skip_unit_tests }}
    name: Run unit tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit
    permissions:
      checks: write
      pull-requests: write

  package:  # Package the Piper task and publish to marketplace (development version)
    if: ${{ github.actor != 'ospo-renovate[bot]' }}  # Avoid publishing the task for dependabot PR's
    uses: ./.github/workflows/package_task.yml
    secrets: inherit
    needs: [versioning, unit-tests]
    with:
      release: false
      node_version: 20.x
      version: ${{ needs.versioning.outputs.version }}
