Init:
  unstash: []
  stashes:
    - name: "source"
      includes: "**/*"
      excludes: ".pipeline/**"

'Build':
  unstash: ['source']
  stashes: []

'Central Build':
  unstash: ['source']
  stashes: []

'Pull-Request Voting':
  unstash: ['source']
  stashes: []

'Promote':
  stashes:
    - name: "cumulus"
      includes: "**/lock-run.json"

'Post Actions':
  unstash: ['cumulus']
  stashes: []
