name: CTP Scan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 10 * *" # 05:00 at 10th of the month
jobs:
  piper:
    uses: project-piper/piper-pipeline-github/.github/workflows/sap-ctp-scan.yml@CTPscan
    secrets: inherit
    permissions:
      contents: read
      id-token: write
